Properly expanding MOPE_DIR and ensuring it exists.

diff --git a/libexec/mope b/libexec/mope
--- a/libexec/mope
+++ b/libexec/mope
@@ -34,7 +34,12 @@ export MOPE_ROOT
 if [ -z "${MOPE_DIR}" ]; then
 	MOPE_DIR="$(pwd)"
 else
-	MOPE_DIR="$(abs_dirname "$MOPE_DIR")"
+	cd "$MOPE_DIR" 2>/dev/null || {
+		echo "mope: cannot change working directory to \`$MOPE_DIR'"
+		exit 1
+	} >&2
+	MOPE_DIR="$(pwd)"
+	cd "$OLDPWD"
 fi
 export MOPE_DIR
 
